{
 "title": "Gin",
 "tags": [ "Service" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(gin_requests_total, job)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(gin_requests_total, method)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(gin_requests_total, status)"
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h,12h,1d" },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Service last updated",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - gin_uptime{job=~\"$job\"}) * 1000"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(gin_requests_total{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests QPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gin_requests_total{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{method}} {{code}} {{url}}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "gin_uptime{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Request size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(gin_request_size_bytes_sum{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(gin_request_size_bytes_count{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{method}} {{code}} {{url}}"
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(gin_request_duration_seconds_sum{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])\r\n/\r\nrate(gin_request_duration_seconds_count{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(gin_request_duration_seconds_bucket{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])) by (le))"
    }
   ]
  },
  {
   "title": "Response size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gin_response_size_bytes_sum{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(gin_response_size_bytes_count{job=~\"$job\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{method}} {{code}} {{url}}"
    }
   ]
  }
 ]
}